services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BeechIt\Bynder\:
    resource: '../Classes/*'

  fluid_view.bynder:
    class: TYPO3Fluid\Fluid\View\ViewInterface
    factory: '@BeechIt\Bynder\Factory\StandaloneViewFactory'

  storage.bynder:
    class: TYPO3\CMS\Core\Resource\ResourceStorageInterface
    factory: '@BeechIt\Bynder\Factory\BynderStorageFactory'

  indexer.bynder_storage:
    class: TYPO3\CMS\Core\Resource\Index\Indexer
    arguments:
      $storage: '@storage.bynder'

  client.bynder:
    class: Bynder\Api\BynderClient
    factory: '@BeechIt\Bynder\Factory\BynderClientFactory'

  BeechIt\Bynder\Service\BynderService:
    arguments:
      $bynderClient: '@client.bynder'

  BeechIt\Bynder\Controller\CompactViewController:
    public: true
    arguments:
      $bynderStorage: '@storage.bynder'
      $view: '@fluid_view.bynder'
      $indexer: '@indexer.bynder_storage'

  BeechIt\Bynder\EventListener\PersistBynderFileStorage:
    tags:
      - name: event.listener
        identifier: 'bynder::persistStorage'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent

  BeechIt\Bynder\EventListener\ProcessBynderAsset:
    tags:
      - name: event.listener
        identifier: 'bynder::processAsset'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  BeechIt\Bynder\EventListener\PublicBynderUrl:
    tags:
      - name: event.listener
        identifier: 'bynder::publicUrl'
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent
